/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Utilitario.ConectaBanco;
import Utilitario.ModeloTabela;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Uildson
 */
public class JFrmProduto extends javax.swing.JFrame {
    ConectaBanco conectaBanco = new ConectaBanco();
    /**
     * Creates new form jFrmProduto
     */
    public JFrmProduto() {
        initComponents();
        conectaBanco.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTproNome = new javax.swing.JTextField();
        jTproFornecedor = new javax.swing.JTextField();
        jTproQtdEstoque = new javax.swing.JTextField();
        jTproPrecoUnit = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuNovo = new javax.swing.JMenu();
        jMenuConsultar = new javax.swing.JMenu();
        jMenuEditar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Produto");
        setResizable(false);

        jLabel1.setText("Nome");

        jLabel3.setText("Fornecedor");

        jLabel4.setText("Qtd. em Estoque");

        jLabel5.setText("Preço Unitario");

        jTproNome.setEnabled(false);

        jTproFornecedor.setEnabled(false);
        jTproFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTproFornecedorActionPerformed(evt);
            }
        });

        jTproQtdEstoque.setEnabled(false);

        jTproPrecoUnit.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Cadastrar produto");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel6.setFocusable(false);

        jButton1.setText("Salvar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenuNovo.setText("Novo");
        jMenuNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuNovoMouseClicked(evt);
            }
        });
        jMenuNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuNovoActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuNovo);

        jMenuConsultar.setText("Consultar");
        jMenuConsultar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuConsultarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jMenuConsultarMouseEntered(evt);
            }
        });
        jMenuBar1.add(jMenuConsultar);

        jMenuEditar.setText("Editar");
        jMenuEditar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEditarMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuEditar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTproNome, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTproFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTproPrecoUnit)
                                .addComponent(jTproQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel6)
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTproNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTproFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jTproQtdEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTproPrecoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(103, 103, 103))
        );

        setSize(new java.awt.Dimension(753, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTproFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTproFornecedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTproFornecedorActionPerformed

   
    private void jMenuNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuNovoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuNovoActionPerformed

    private void jMenuNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuNovoMouseClicked
    
        
        jTproNome.setEnabled(true);
        jTproNome.setEditable(true);
        jTproFornecedor.setEnabled(true);
        jTproFornecedor.setEditable(true);
        jTproQtdEstoque.setEnabled(true);
        jTproQtdEstoque.setEditable(true);
        jTproPrecoUnit.setEnabled(true);
        jTproPrecoUnit.setEditable(true);
    
    }//GEN-LAST:event_jMenuNovoMouseClicked

    private void jMenuConsultarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConsultarMouseEntered

    }//GEN-LAST:event_jMenuConsultarMouseEntered

    private void jMenuConsultarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuConsultarMouseClicked

        
        jTproNome.setEnabled(true);
        jTproNome.setEditable(false);
        jTproFornecedor.setEnabled(true);
        jTproFornecedor.setEditable(false);
        jTproQtdEstoque.setEnabled(true);
        jTproQtdEstoque.setEditable(false);
        jTproPrecoUnit.setEnabled(true);
        jTproPrecoUnit.setEditable(false);
       
    }//GEN-LAST:event_jMenuConsultarMouseClicked

    private void jMenuEditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEditarMouseClicked
        // TODO add your handling code here:
        jTproNome.setText(" "); //limpa a caixa de texto
        //jTproFornecedor.setText(" "); //limpa a caixa de texto
        //jTproQtdEstoque.setText(" "); //limpa a caixa de texto
        //jTproPrecoUnit.setText(" "); //limpa a caixa de texto

       
        jTproNome.setEnabled(true);
        jTproNome.setEditable(true);
        jTproFornecedor.setEnabled(true);
        jTproFornecedor.setEditable(true);
        jTproQtdEstoque.setEnabled(true);
        jTproQtdEstoque.setEditable(true);
        jTproPrecoUnit.setEnabled(true);
        jTproPrecoUnit.setEditable(true);
  
    }//GEN-LAST:event_jMenuEditarMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void preencherTabela(String SQL){
        ArrayList dados = new ArrayList();
        
        String[] colunas = new String[]{"idPro","nome","fornecedor","qtdEstoque","precoUnit"};
         conectaBanco.executaSQL(SQL);
         try {
            conectaBanco.rs.first();
            do{
                dados.add(new Object[]{conectaBanco.rs.getInt("idPro"), conectaBanco.rs.getString("nome"),conectaBanco.rs.getString("fornecedor"), conectaBanco.rs.getInt("qtdEstoque"), conectaBanco.rs.getFloat("precoUnit")});
                
            }while(conectaBanco.rs.next());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Preencher o ArrayList! \n ERRO: " +ex);
        }
        // ModeloTabela modelo = new ModeloTabela(dados, Colunas);
         //jTableProduto.setModel(modelo);
         
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrmProduto().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultar;
    private javax.swing.JMenu jMenuEditar;
    private javax.swing.JMenu jMenuNovo;
    private javax.swing.JTextField jTproFornecedor;
    private javax.swing.JTextField jTproNome;
    private javax.swing.JTextField jTproPrecoUnit;
    private javax.swing.JTextField jTproQtdEstoque;
    // End of variables declaration//GEN-END:variables

 

    public javax.swing.JTextField getjTproFornecedor() {
        return jTproFornecedor;
    }

    public void setjTproFornecedor(javax.swing.JTextField jTproFornecedor) {
        this.jTproFornecedor = jTproFornecedor;
    }


    public javax.swing.JTextField getjTproNome() {
        return jTproNome;
    }

    public void setjTproNome(javax.swing.JTextField jTproNome) {
        this.jTproNome = jTproNome;
    }

    public javax.swing.JTextField getjTproPrecoUnit() {
        return jTproPrecoUnit;
    }

    public void setjTproPrecoUnit(javax.swing.JTextField jTproPrecoUnit) {
        this.jTproPrecoUnit = jTproPrecoUnit;
    }

    public javax.swing.JTextField getjTproQtdEstoque() {
        return jTproQtdEstoque;
    }

    public void setjTproQtdEstoque(javax.swing.JTextField jTproQtdEstoque) {
        this.jTproQtdEstoque = jTproQtdEstoque;
    }
}

